name: CI
on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Evaluate app version
        run: |
          echo "APP_VERSION=$(date '+%Y-%m-%d')-$(git rev-parse HEAD | cut -c -6)" >> "$GITHUB_ENV"

      - name: Pull existing image for layer cache
        run: docker pull funbiscuit/passphrase:latest

      - name: Build docker image
        run: docker build . -t "funbiscuit/passphrase:$APP_VERSION" --cache-from funbiscuit/passphrase:latest

      - name: Add latest tag
        run: docker tag "funbiscuit/passphrase:$APP_VERSION" funbiscuit/passphrase:latest

      - name: Test image
        run: docker run --rm funbiscuit/passphrase

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: funbiscuit
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: docker push "funbiscuit/passphrase:$APP_VERSION" && docker push funbiscuit/passphrase:latest
